#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


remote_IP=$1
peruse_IP=$2
peruse_Port=$3
remote_user=$4

. lg-potree-stop $remote_IP $remote_user

device_id='/dev/input/spacenavigator'

killall node nodejs spacenav-emitter;

echo "Opening lg-potree on $peruse_IP":"$peruse_Port"
${HOME}/asherat666-peruse-a-rue/bin/peruse-a-rue &
${HOME}/asherat666-peruse-a-rue/bin/spacenav-emitter 127.0.0.1 $peruse_Port &


#Run chromiums
remote_cmd='. ${HOME}/etc/shell.conf;

lg-ctl-master;

for lg in $LG_FRAMES ; do
	frame=$(($(echo $lg | cut -c 3)-1));

	if [[ ${frame} -gt $(( ${LG_FRAMES_MAX}/2 )) ]] ; then
	    frame=$(( ${frame} - ${LG_FRAMES_MAX} ));
	fi

	CMD0="killall chromium-browser; export DISPLAY=:0 && chromium-browser '$peruse_IP':'$peruse_Port'/lg-potree/";
	if [[ $frame -eq 0 ]]
	then
		CMD=$CMD0;
	else

		CMD=$CMD0"slave.html?yawOffset="$frame;
	fi

	ssh -x '$remote_user'@$lg $CMD &	

done
';

ssh -x lg@$remote_IP "$remote_cmd" &
