#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. ${HOME}/etc/shell.conf
nodeServerPath="${HOME}/asherat666-peruse-a-rue/bin/peruse-a-rue"

[ -z "${LG_FRAMES}" ] && echo "LG_FRAMES is empty" && exit 1

if [ $# -ne 2 ] ; then
    echo "USAGE: $0 [Peruse Server IP]  [Port]"
	peruse_ip="lg1"
	port="8086"
else
	peruse_ip=$1
	port=$2
fi

#lg-run "killall -q chromium-browser;" &
ssh -tt -x lg@lg1 "killall -q node;"

ssh -x lg@lg1 "$nodeServerPath $peruse_ip $port" &
echo "Opening lg-potree on $peruse_ip:$port"

lg-ctl-master

for lg in $LG_FRAMES ; do
	frame=$(($(echo $lg | cut -c 3)-1))

	if [[ ${frame} -gt $(( ${LG_FRAMES_MAX}/2 )) ]] ; then
	    frame="$(( ${frame} - ${LG_FRAMES_MAX} ))"
	fi

	CMD0="export DISPLAY=:0 && chromium-browser '\\$peruse_ip'\\:$port/lg-potree/"
	if [[ $frame -eq 0 ]]
	then
		CMD=$CMD0
	else

		CMD=$CMD0"slave.html?yawOffset=$frame"
	fi

	echo "$CMD"
	
	ssh -x lg@$lg "$CMD" &

done

exit 0
