#!/bin/bash
# Copyright 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. lg-potree-stop

peruse_IP=$1
peruse_Port=$2
remote_IP=$3

device_id='/dev/input/spacenavigator'

 nodeServerPath='$HOME/asherat666-peruse-a-rue/bin/peruse-a-rue';
 controllerPath='$HOME/asherat666-peruse-a-rue/spacenav-emitter /dev/input/spacenavigator 127.0.0.1 '$peruse_Port;
 
 
#Run chromiums
remote_cmd='. ${HOME}/etc/shell.conf
		for lg in $LG_FRAMES ; do
			frame=$(($(echo $lg | cut -c 3)-1));
			if [[ ${frame} -gt $(( ${LG_FRAMES_MAX}/2 )) ]]; then
				frame="$(( ${frame} - ${LG_FRAMES_MAX} ))";
			fi
			CMD="killall chromium-browser; export DISPLAY=:0.0 && chromium-browser '$peruse_IP':'$peruse_Port'/lg-potree/"
			if [[ $frame -ne 0 ]] ; then
				CMD=$CMD"slave.html?yawOffset="$frame;
			fi
			ssh -x lg@$lg "$CMD" &
		done';

exec $nodeServerPath &
exec $controllerPath &
ssh -x lg@$remote_IP "$remote_cmd" &
